# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/sbin/cmake

# The command to remove a file.
RM = /usr/sbin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maseus/Gizmo/gizmo-dev

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maseus/Gizmo/gizmo-dev

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/sbin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/sbin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/sbin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/sbin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/sbin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/sbin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/sbin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/sbin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maseus/Gizmo/gizmo-dev/CMakeFiles /home/maseus/Gizmo/gizmo-dev//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maseus/Gizmo/gizmo-dev/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gizmo

# Build rule for target.
gizmo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gizmo
.PHONY : gizmo

# fast build rule for target.
gizmo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/build
.PHONY : gizmo/fast

#=============================================================================
# Target rules for targets named ggml-base

# Build rule for target.
ggml-base: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-base
.PHONY : ggml-base

# fast build rule for target.
ggml-base/fast:
	$(MAKE) $(MAKESILENT) -f llama.cpp/ggml/src/CMakeFiles/ggml-base.dir/build.make llama.cpp/ggml/src/CMakeFiles/ggml-base.dir/build
.PHONY : ggml-base/fast

#=============================================================================
# Target rules for targets named ggml

# Build rule for target.
ggml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml
.PHONY : ggml

# fast build rule for target.
ggml/fast:
	$(MAKE) $(MAKESILENT) -f llama.cpp/ggml/src/CMakeFiles/ggml.dir/build.make llama.cpp/ggml/src/CMakeFiles/ggml.dir/build
.PHONY : ggml/fast

#=============================================================================
# Target rules for targets named ggml-cpu

# Build rule for target.
ggml-cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ggml-cpu
.PHONY : ggml-cpu

# fast build rule for target.
ggml-cpu/fast:
	$(MAKE) $(MAKESILENT) -f llama.cpp/ggml/src/CMakeFiles/ggml-cpu.dir/build.make llama.cpp/ggml/src/CMakeFiles/ggml-cpu.dir/build
.PHONY : ggml-cpu/fast

#=============================================================================
# Target rules for targets named llama

# Build rule for target.
llama: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 llama
.PHONY : llama

# fast build rule for target.
llama/fast:
	$(MAKE) $(MAKESILENT) -f llama.cpp/src/CMakeFiles/llama.dir/build.make llama.cpp/src/CMakeFiles/llama.dir/build
.PHONY : llama/fast

#=============================================================================
# Target rules for targets named vendor-hash

# Build rule for target.
vendor-hash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vendor-hash
.PHONY : vendor-hash

# fast build rule for target.
vendor-hash/fast:
	$(MAKE) $(MAKESILENT) -f llama.cpp/vendor/hash/CMakeFiles/vendor-hash.dir/build.make llama.cpp/vendor/hash/CMakeFiles/vendor-hash.dir/build
.PHONY : vendor-hash/fast

#=============================================================================
# Target rules for targets named gizmo_one_block_spike

# Build rule for target.
gizmo_one_block_spike: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gizmo_one_block_spike
.PHONY : gizmo_one_block_spike

# fast build rule for target.
gizmo_one_block_spike/fast:
	$(MAKE) $(MAKESILENT) -f tools/one_block_spike/CMakeFiles/gizmo_one_block_spike.dir/build.make tools/one_block_spike/CMakeFiles/gizmo_one_block_spike.dir/build
.PHONY : gizmo_one_block_spike/fast

#=============================================================================
# Target rules for targets named gizmo_sharded_engine_core

# Build rule for target.
gizmo_sharded_engine_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gizmo_sharded_engine_core
.PHONY : gizmo_sharded_engine_core

# fast build rule for target.
gizmo_sharded_engine_core/fast:
	$(MAKE) $(MAKESILENT) -f tools/sharded_engine/CMakeFiles/gizmo_sharded_engine_core.dir/build.make tools/sharded_engine/CMakeFiles/gizmo_sharded_engine_core.dir/build
.PHONY : gizmo_sharded_engine_core/fast

#=============================================================================
# Target rules for targets named gizmo_sharded_engine

# Build rule for target.
gizmo_sharded_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gizmo_sharded_engine
.PHONY : gizmo_sharded_engine

# fast build rule for target.
gizmo_sharded_engine/fast:
	$(MAKE) $(MAKESILENT) -f tools/sharded_engine/CMakeFiles/gizmo_sharded_engine.dir/build.make tools/sharded_engine/CMakeFiles/gizmo_sharded_engine.dir/build
.PHONY : gizmo_sharded_engine/fast

#=============================================================================
# Target rules for targets named gizmo_argmax_probe

# Build rule for target.
gizmo_argmax_probe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gizmo_argmax_probe
.PHONY : gizmo_argmax_probe

# fast build rule for target.
gizmo_argmax_probe/fast:
	$(MAKE) $(MAKESILENT) -f tools/sharded_engine/CMakeFiles/gizmo_argmax_probe.dir/build.make tools/sharded_engine/CMakeFiles/gizmo_argmax_probe.dir/build
.PHONY : gizmo_argmax_probe/fast

#=============================================================================
# Target rules for targets named gizmo_argmax_dump

# Build rule for target.
gizmo_argmax_dump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gizmo_argmax_dump
.PHONY : gizmo_argmax_dump

# fast build rule for target.
gizmo_argmax_dump/fast:
	$(MAKE) $(MAKESILENT) -f tools/sharded_engine/CMakeFiles/gizmo_argmax_dump.dir/build.make tools/sharded_engine/CMakeFiles/gizmo_argmax_dump.dir/build
.PHONY : gizmo_argmax_dump/fast

#=============================================================================
# Target rules for targets named gizmo_ref_per_layer_dump

# Build rule for target.
gizmo_ref_per_layer_dump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gizmo_ref_per_layer_dump
.PHONY : gizmo_ref_per_layer_dump

# fast build rule for target.
gizmo_ref_per_layer_dump/fast:
	$(MAKE) $(MAKESILENT) -f tools/sharded_engine/CMakeFiles/gizmo_ref_per_layer_dump.dir/build.make tools/sharded_engine/CMakeFiles/gizmo_ref_per_layer_dump.dir/build
.PHONY : gizmo_ref_per_layer_dump/fast

#=============================================================================
# Target rules for targets named gizmo_diff_per_layer

# Build rule for target.
gizmo_diff_per_layer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gizmo_diff_per_layer
.PHONY : gizmo_diff_per_layer

# fast build rule for target.
gizmo_diff_per_layer/fast:
	$(MAKE) $(MAKESILENT) -f tools/sharded_engine/CMakeFiles/gizmo_diff_per_layer.dir/build.make tools/sharded_engine/CMakeFiles/gizmo_diff_per_layer.dir/build
.PHONY : gizmo_diff_per_layer/fast

src/chat/handler.o: src/chat/handler.cpp.o
.PHONY : src/chat/handler.o

# target to build an object file
src/chat/handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/chat/handler.cpp.o
.PHONY : src/chat/handler.cpp.o

src/chat/handler.i: src/chat/handler.cpp.i
.PHONY : src/chat/handler.i

# target to preprocess a source file
src/chat/handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/chat/handler.cpp.i
.PHONY : src/chat/handler.cpp.i

src/chat/handler.s: src/chat/handler.cpp.s
.PHONY : src/chat/handler.s

# target to generate assembly for a file
src/chat/handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/chat/handler.cpp.s
.PHONY : src/chat/handler.cpp.s

src/cli/parser.o: src/cli/parser.cpp.o
.PHONY : src/cli/parser.o

# target to build an object file
src/cli/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/cli/parser.cpp.o
.PHONY : src/cli/parser.cpp.o

src/cli/parser.i: src/cli/parser.cpp.i
.PHONY : src/cli/parser.i

# target to preprocess a source file
src/cli/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/cli/parser.cpp.i
.PHONY : src/cli/parser.cpp.i

src/cli/parser.s: src/cli/parser.cpp.s
.PHONY : src/cli/parser.s

# target to generate assembly for a file
src/cli/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/cli/parser.cpp.s
.PHONY : src/cli/parser.cpp.s

src/inference/engine.o: src/inference/engine.cpp.o
.PHONY : src/inference/engine.o

# target to build an object file
src/inference/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/inference/engine.cpp.o
.PHONY : src/inference/engine.cpp.o

src/inference/engine.i: src/inference/engine.cpp.i
.PHONY : src/inference/engine.i

# target to preprocess a source file
src/inference/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/inference/engine.cpp.i
.PHONY : src/inference/engine.cpp.i

src/inference/engine.s: src/inference/engine.cpp.s
.PHONY : src/inference/engine.s

# target to generate assembly for a file
src/inference/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/inference/engine.cpp.s
.PHONY : src/inference/engine.cpp.s

src/layer/manager.o: src/layer/manager.cpp.o
.PHONY : src/layer/manager.o

# target to build an object file
src/layer/manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/layer/manager.cpp.o
.PHONY : src/layer/manager.cpp.o

src/layer/manager.i: src/layer/manager.cpp.i
.PHONY : src/layer/manager.i

# target to preprocess a source file
src/layer/manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/layer/manager.cpp.i
.PHONY : src/layer/manager.cpp.i

src/layer/manager.s: src/layer/manager.cpp.s
.PHONY : src/layer/manager.s

# target to generate assembly for a file
src/layer/manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/layer/manager.cpp.s
.PHONY : src/layer/manager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model/manager.o: src/model/manager.cpp.o
.PHONY : src/model/manager.o

# target to build an object file
src/model/manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/model/manager.cpp.o
.PHONY : src/model/manager.cpp.o

src/model/manager.i: src/model/manager.cpp.i
.PHONY : src/model/manager.i

# target to preprocess a source file
src/model/manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/model/manager.cpp.i
.PHONY : src/model/manager.cpp.i

src/model/manager.s: src/model/manager.cpp.s
.PHONY : src/model/manager.s

# target to generate assembly for a file
src/model/manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/model/manager.cpp.s
.PHONY : src/model/manager.cpp.s

src/util/proc_status.o: src/util/proc_status.cpp.o
.PHONY : src/util/proc_status.o

# target to build an object file
src/util/proc_status.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/util/proc_status.cpp.o
.PHONY : src/util/proc_status.cpp.o

src/util/proc_status.i: src/util/proc_status.cpp.i
.PHONY : src/util/proc_status.i

# target to preprocess a source file
src/util/proc_status.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/util/proc_status.cpp.i
.PHONY : src/util/proc_status.cpp.i

src/util/proc_status.s: src/util/proc_status.cpp.s
.PHONY : src/util/proc_status.s

# target to generate assembly for a file
src/util/proc_status.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gizmo.dir/build.make CMakeFiles/gizmo.dir/src/util/proc_status.cpp.s
.PHONY : src/util/proc_status.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ggml"
	@echo "... ggml-base"
	@echo "... ggml-cpu"
	@echo "... gizmo"
	@echo "... gizmo_argmax_dump"
	@echo "... gizmo_argmax_probe"
	@echo "... gizmo_diff_per_layer"
	@echo "... gizmo_one_block_spike"
	@echo "... gizmo_ref_per_layer_dump"
	@echo "... gizmo_sharded_engine"
	@echo "... gizmo_sharded_engine_core"
	@echo "... llama"
	@echo "... vendor-hash"
	@echo "... src/chat/handler.o"
	@echo "... src/chat/handler.i"
	@echo "... src/chat/handler.s"
	@echo "... src/cli/parser.o"
	@echo "... src/cli/parser.i"
	@echo "... src/cli/parser.s"
	@echo "... src/inference/engine.o"
	@echo "... src/inference/engine.i"
	@echo "... src/inference/engine.s"
	@echo "... src/layer/manager.o"
	@echo "... src/layer/manager.i"
	@echo "... src/layer/manager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model/manager.o"
	@echo "... src/model/manager.i"
	@echo "... src/model/manager.s"
	@echo "... src/util/proc_status.o"
	@echo "... src/util/proc_status.i"
	@echo "... src/util/proc_status.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

